### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kanishkegb** [fdcl-gwu/fdcl_FFTSO3#3]
Now this repo has travis-CI, unit tests and all, I have few suggestions to improve this further:
1. make the file naming consistent: `/inlcude` has header files with both `*.hpp` and `*.h`, we should rename them to be consistent
2. remove `using namespace xxx` from header files: it is [a bad idea](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice) to use `using namespace xxx` in general, and specifically in header files as it might raise conflicts in files in which these header files are included - we should either get rid of them (using `std::cout` instead of `cout`) or move them to the respective `*.cpp` file
3. using Doxygen or something similar for documentation

**Comment by tylee-fdcl** [comment]
using namespace avoided
